### cadastro de meliponicultor

POST http://localhost:3000/meliponicultores
Content-Type: application/json

{
    "nome": "Luiz",
    "email": "luiz@email.com",
    "senha": "123",
    "cpf": "1234",
    "cidade": "João Pessoa",
    "telefone": "83911112222"
}